# golangci-lint configuration
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  gosec:
    excludes:
      - G101

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
